//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.28 at 04:34:58 PM EET 
//


package preprod.qa.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the preprod.qa.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: preprod.qa.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateBookingResponse }
     * 
     */
    public UpdateBookingResponse createUpdateBookingResponse() {
        return new UpdateBookingResponse();
    }

    /**
     * Create an instance of {@link Booking }
     * 
     */
    public Booking createBooking() {
        return new Booking();
    }

    /**
     * Create an instance of {@link GetBookingByDoctorNameResponse }
     * 
     */
    public GetBookingByDoctorNameResponse createGetBookingByDoctorNameResponse() {
        return new GetBookingByDoctorNameResponse();
    }

    /**
     * Create an instance of {@link AddBookingResponse }
     * 
     */
    public AddBookingResponse createAddBookingResponse() {
        return new AddBookingResponse();
    }

    /**
     * Create an instance of {@link RemoveBookingRequest }
     * 
     */
    public RemoveBookingRequest createRemoveBookingRequest() {
        return new RemoveBookingRequest();
    }

    /**
     * Create an instance of {@link AddBookingRequest }
     * 
     */
    public AddBookingRequest createAddBookingRequest() {
        return new AddBookingRequest();
    }

    /**
     * Create an instance of {@link UpdateBookingRequest }
     * 
     */
    public UpdateBookingRequest createUpdateBookingRequest() {
        return new UpdateBookingRequest();
    }

    /**
     * Create an instance of {@link RemoveBookingResponse }
     * 
     */
    public RemoveBookingResponse createRemoveBookingResponse() {
        return new RemoveBookingResponse();
    }

    /**
     * Create an instance of {@link GetBookingByDoctorNameRequest }
     * 
     */
    public GetBookingByDoctorNameRequest createGetBookingByDoctorNameRequest() {
        return new GetBookingByDoctorNameRequest();
    }

    /**
     * Create an instance of {@link GetBookingByDoctorNameAndTimeSlotResponse }
     * 
     */
    public GetBookingByDoctorNameAndTimeSlotResponse createGetBookingByDoctorNameAndTimeSlotResponse() {
        return new GetBookingByDoctorNameAndTimeSlotResponse();
    }

    /**
     * Create an instance of {@link GetBookingByDoctorNameAndTimeSlotRequest }
     * 
     */
    public GetBookingByDoctorNameAndTimeSlotRequest createGetBookingByDoctorNameAndTimeSlotRequest() {
        return new GetBookingByDoctorNameAndTimeSlotRequest();
    }

    /**
     * Create an instance of {@link GetBookingByTimeSetResponse }
     * 
     */
    public GetBookingByTimeSetResponse createGetBookingByTimeSetResponse() {
        return new GetBookingByTimeSetResponse();
    }

    /**
     * Create an instance of {@link GetBookingByTimeSetRequest }
     * 
     */
    public GetBookingByTimeSetRequest createGetBookingByTimeSetRequest() {
        return new GetBookingByTimeSetRequest();
    }

    /**
     * Create an instance of {@link Doctor }
     * 
     */
    public Doctor createDoctor() {
        return new Doctor();
    }

}
