//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.28 at 04:34:58 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://preprod/qa/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package preprod.qa.soap;
